
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: gs
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      restartPolicy: Always
      containers:
      - name: api
        image: dockergreennew.azurecr.io/api
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 150m
   
---

apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: gs
  annotations:
    service.beta.kubernetes.io/azure-load-balancer: "true"
spec:
  selector:
    app: api
  type: LoadBalancer   
  ports:
  - name: http
    port: 3000
    targetPort: 3000

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api
  namespace: gs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 1
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40

